apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: traefik
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
      sectionName: web
  hostnames:
    - kiddify.pl
    - www.kiddify.pl
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
    - matches:
        - path:
            type: PathPrefix
            value: "/.well-known/acme-challenge"
      backendRefs:
        - name: cm-acme-http-solver
          namespace: cert-manager
          port: 8089
