#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg

runcmd:
  #Instalacja containerd
  - apt-get update
  - apt-get install -y ca-certificates
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y containerd.io

  #Konfiguracja containerd https://kubernetes.io/docs/setup/production-environment/container-runtimes/
  - mkdir -p /etc/containerd
  - containerd config default > /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl enable containerd
  - systemctl restart containerd

  #Konfiguracja systemu
  - sed -i '/ swap / s/^/#/' /etc/fstab
  - swapoff -a

  #Konfiguracja kernela
  - modprobe overlay
  - modprobe br_netfilter
  - |
    cat <<EOF | tee /etc/modules-load.d/k8s.conf
    overlay
    br_netfilter
    EOF
  - |
    cat <<EOF | tee /etc/sysctl.d/kubernetes.conf
    net.ipv4.ip_forward = 1
    EOF
  - sysctl --system

  #Instalacja kubelet, kubeadm, kubectl
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - apt-get update
  - apt-get install -y apt-transport-https ca-certificates curl gpg
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl
  - systemctl enable --now kubelet

  #Inciajlizacja clustra pod Calico
  - kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=$(hostname -I | awk '{print $1}')
  - mkdir -p /root/.kube
  - sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
  - sudo chown root:root /root/.kube/config

  #Instalacja Calico CNI
  - export KUBECONFIG=/etc/kubernetes/admin.conf
  - kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=600s
  - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/tigera-operator.yaml
  - kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml
  - sleep 60
  - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/custom-resources.yaml
  - |
    TIMEOUT=600
    ELAPSED=0
    while [ $(kubectl get nodes --no-headers | grep -v "control-plane" | grep " Ready" | wc -l) -lt 1 ] && [ $ELAPSED -lt $TIMEOUT ]; do
      sleep 10
      ELAPSED=$((ELAPSED + 10))
    done
    if [ $(kubectl get nodes --no-headers | grep -v "control-plane" | grep " Ready" | wc -l) -lt 1 ]; then
      echo "ERROR: No worker nodes has joined the cluster"
      exit 1
    fi

  # Instalacja LCP (Storage Class)
  - kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
  - kubectl wait --for=condition=Available deployment/local-path-provisioner -n local-path-storage --timeout=300s
  - kubectl patch storageclass local-path -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - kubectl create namespace argocd
  - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - kubectl wait --for=condition=Ready pods --all -n argocd --timeout=600s
  - |
    kubectl patch svc argocd-server -n argocd --patch '{
      "spec": {
        "type": "LoadBalancer"
      }
    }'
  - helm repo add traefik https://traefik.github.io/charts
  - helm repo update
  - kubectl create namespace traefik
  - |
    cat <<EOF > /root/traefik-cfg.yml
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false

    service:
      type: NodePort
    EOF

  - helm install traefik traefik/traefik -n traefik -f /root/traefik-cfg.yml
  - kubectl wait --for=condition=Ready pods --all -n traefik --timeout=600s
  - |
    kubectl apply -f - <<EOF
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: git-cd
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/kiszkahubert/final-prj.git
        targetRevision: master
        path: terraform/kubernetes
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
    EOF